version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: zinara-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zinara_admin
      POSTGRES_PASSWORD: zinara_secure_pwd_2025
      POSTGRES_DB: zinara_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zinara_admin -d zinara_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zinara-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass zinara_redis_pwd_2025 --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "zinara_redis_pwd_2025", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
